name: markup
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  path: ^1.8.3
  path_provider: ^2.1.5
  dartssh2: ^2.5.0
  window_size: ^0.1.0

dev_dependencies:
  mocktail: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
